[build]
  command = "pip install -r requirements.txt"
  publish = "templates"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  [[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200
